//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int u_userId { get; set; }
        public int ut_userTypeId { get; set; }
        public string u_login { get; set; }
        public string u_password { get; set; }
        public string u_firstName { get; set; }
        public string u_lastName { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
