//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBankDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int p_paymentId { get; set; }
        public int pt_paymentTypeId { get; set; }
        public int u_userId { get; set; }
        public decimal p_payment { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual User User { get; set; }
    }
}
